name: CICD-example

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Build stage
        run: |
          echo "Building..."

  test:
    runs-on: self-hosted
    needs: [build]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test stage
        run: |
          echo "Testing..."
 
  Deploy:
    runs-on: self-hosted
    needs: [test]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy stage
        run: |
          echo "Deploying..."    