name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # CHANGE TO YOUR BRANCH
  push:
    branches: [ main ]



jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Building docker images
        run: |
          cd app
          docker --version
 
