name: CICD-example

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:18.04
    steps:
      - name: Build 
        run: |
          echo "Building..."
          echo "Im running inside of the container"
          ls

  test:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Test 
        run: |
          echo "Testing..."
 
  Deploy:
    runs-on: self-hosted
    needs: [test]
    steps:
      - name: Deploy 
        run: |
          echo "Deploying..."    