name: CICD-example

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build 
        run: |
          echo "Building"

  test:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Test 
        run: |
          echo "Testing"
 
  Deploy:
    runs-on: self-hosted
    needs: [test]
    steps:
      - name: Deploy 
        run: |
          echo "Deploying"    